apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::568947653646:role/UdacityFlaskDeployCBKubectlRole
      username: build 
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::568947653646:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-NLHSE1H6N9KC
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-05-26T06:06:45Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2021-05-26T06:06:45Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2578"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 0e247c6f-0d91-4343-8619-6881e1575357
